export const SET_COUNT = 'SET_COUNT'; // 设置异步请求后台挖掘的数量
export const SET_PARTS = 'SET_PARTS';
export const SET_PARTS_DAYS = 'SET_PARTS_DAYS';
export const SET_STARTTIME = 'SET_STARTTIME';
export const SET_ENDTIME = 'SET_ENDTIME';
export const SET_TYPE = 'SET_TYPE';
export const SET_TYPE_INDEX = 'SET_TYPE_INDEX';
export const SET_DAYS_TYPE = 'SET_DAYS_TYPE';
export const SET_DAYS_TYPE_INDEX = 'SET_DAYS_TYPE_INDEX';
export const SET_DAYS_SERIES = 'SET_DAYS_SERIES';
export const SET_DAYS_REPORTTIMES = 'SET_DAYS_REPORTTIMES';
// export const SET_DAY_PARAMS = 'SET_DAY_PARAMS';
export const SET_DAYS_PARAMS = 'SET_DAYS_PARAMS';
export const SET_BADCHART_STARTTIME = 'SET_BADCHART_STARTTIME';
export const SET_BADCHART_ENDTIME = 'SET_BADCHART_ENDTIME'; 
export const SET_BADCHART_TYPE = 'SET_BADCHART_TYPE';
export const SET_BADCHART_TYPE_INDEX = 'SET_BADCHART_TYPE_INDEX';
export const SET_BADCHART_ITEM = 'SET_BADCHART_ITEM';
export const SET_BADCHART_SEARCHPARAMS = 'SET_BADCHART_SEARCHPARAMS'; 
export const SET_STOREPICK_TYPE = 'SET_STOREPICK_TYPE';
export const SET_STOREPICK_INDEX = 'SET_STOREPICK_INDEX'; 
export const SET_STOREPICK_STARTTIME = 'SET_STOREPICK_STARTTIME';
export const SET_STOREPICK_ENDTIME = 'SET_STOREPICK_ENDTIME';
export const SET_COMPARESTORE_TYPE = 'SET_COMPARESTORE_TYPE';
export const SET_COMPARESTORE_INDEX = 'SET_COMPARESTORE_INDEX';
export const SET_COMPARESTORE_MODELS = 'SET_COMPARESTORE_MODELS';
export const SET_BADINFORMATION_TYPE = 'SET_BADINFORMATION_TYPE';
export const SET_BADINFORMATION_INDEX = 'SET_BADINFORMATION_INDEX';
export const SET_BADINFORMATION_ITEM = 'SET_BADINFORMATION_ITEM';                  
export const SET_DAYENTREPOT_INITECHART = 'SET_DAYENTREPOT_INITECHART';    

export const SET_DAYENTREPOT_MODELNAMELIST = 'SET_DAYENTREPOT_MODELNAMELIST';       //当天机种名称集合
export const SET_DAYENTREPOT_PARTNOLIST = 'SET_DAYENTREPOT_PARTNOLIST';             //物料号集合
export const SET_DAYENTREPOT_MODELREPORTTATOLSLIST = 'SET_DAYENTREPOT_MODELREPORTTATOLSLIST';       //机种数量集合
export const SET_DAYSENTREPOT_REPORTTIMES = 'SET_DAYSENTREPOT_REPORTTIMES';             //物料号集合
export const SET_DAYSENTREPOT_SERIES = 'SET_DAYSENTREPOT_SERIES';  
export const SET_DAYSENTREPOT_PARTARR = 'SET_DAYSENTREPOT_PARTARR';  
export const SET_BADCHART_BACKDATA = 'SET_BADCHART_BACKDATA';
export const SET_COMPARESTORE_CHART = 'SET_COMPARESTORE_CHART';
export const SET_STOREPICK_DATA = 'SET_STOREPICK_DATA';
export const SET_BADCHART_SHOWSTATE = 'SET_BADCHART_SHOWSTATE';
export const SET_BADCHART_SCROLLBAR = 'SET_BADCHART_SCROLLBAR';
export const SET_STOREPICK_SHOWSTATE = 'SET_STOREPICK_SHOWSTATE';
export const SET_MODELSALERATIO_TYPE = 'SET_MODELSALERATIO_TYPE';
export const SET_MODELSALERATIO_INDEX = 'SET_MODELSALERATIO_INDEX';
export const SET_MODELSALERATIO_STARTTIME = 'SET_MODELSALERATIO_STARTTIME';
export const SET_MODELSALERATIO_ENDTIME = 'SET_MODELSALERATIO_ENDTIME';
export const SET_MODELSALERATIO_PARTS = 'SET_MODELSALERATIO_PARTS';

export const SET_PRODUCTDATA_TYPE = 'SET_PRODUCTDATA_TYPE';
export const SET_PRODUCTDATA_INDEX = 'SET_PRODUCTDATA_INDEX';
export const SET_PRODUCTDATA_STARTTIME = 'SET_PRODUCTDATA_STARTTIME';
export const SET_PRODUCTDATA_ENDTIME = 'SET_PRODUCTDATA_ENDTIME';
export const SET_PRODUCTDATA_PARTS = 'SET_PRODUCTDATA_PARTS';
export const SET_PRODUCTDATA_DATADETAIL = 'SET_PRODUCTDATA_DATADETAIL';

export const SET_MODELSALEDETAIL_TYPE = 'SET_MODELSALEDETAIL_TYPE';
export const SET_MODELSALEDETAIL_INDEX = 'SET_MODELSALEDETAIL_INDEX';
export const SET_MODELSALEDETAIL_STARTTIME = 'SET_MODELSALEDETAIL_STARTTIME';
export const SET_MODELSALEDETAIL_ENDTIME = 'SET_MODELSALEDETAIL_ENDTIME';
export const SET_MODELSALEDETAIL_PARTS = 'SET_MODELSALEDETAIL_PARTS';
export const SET_MODELSALEDETAIL_DATADETAIL = 'SET_MODELSALEDETAIL_DATADETAIL';

export const SET_MODELANDCODE = 'SET_MODELANDCODE';
export const SET_CLASSANDDATE = 'SET_CLASSANDDATE';
export const SET_REPORTTOTALARR = 'SET_REPORTTOTALARR';
export const SET_GRIDDATA = 'SET_GRIDDATA';
export const SET_FORMATGRID = 'SET_FORMATGRID';
export const SET_CONCATOBJ = 'SET_CONCATOBJ';
export const SET_MODELNAMELIST = 'SET_MODELNAMELIST';

export const SET_MANYMODELYIELD_TYPE = 'SET_MANYMODELYIELD_TYPE';
export const SET_MANYMODELYIELD_INDEX = 'SET_MANYMODELYIELD_INDEX';
export const SET_MANYMODELYIELD_STARTTIME = 'SET_MANYMODELYIELD_STARTTIME';
export const SET_MANYMODELYIELD_ENDTIME = 'SET_MANYMODELYIELD_ENDTIME';
export const SET_MANYMODELYIELD_ITEM = 'SET_MANYMODELYIELD_ITEM';
export const SET_MANYMODELYIELD_LIST = 'SET_MANYMODELYIELD_LIST';
export const SET_COUNTTOTALANDYIELD = 'SET_COUNTTOTALANDYIELD';

export const SET_PROCESSPRODUCTION_TYPE = 'SET_PROCESSPRODUCTION_TYPE';
export const SET_PROCESSPRODUCTION_INDEX = 'SET_PROCESSPRODUCTION_INDEX';
export const SET_PROCESSPRODUCTION_ITEM = 'SET_PROCESSPRODUCTION_ITEM';

export const SET_PROCESSCUSTOMER_TYPE = 'SET_PROCESSCUSTOMER_TYPE';
export const SET_PROCESSCUSTOMER_INDEX = 'SET_PROCESSCUSTOMER_INDEX';
export const SET_PROCESSCUSTOMER_ITEM = 'SET_PROCESSCUSTOMER_ITEM';
export const SET_COUNTSTOREPICK_ITEM = 'SET_COUNTSTOREPICK_ITEM';

export const SET_PROCESSINPUTOUT_TYPE = 'SET_PROCESSINPUTOUT_TYPE';
export const SET_PROCESSINPUTOUT_INDEX = 'SET_PROCESSINPUTOUT_INDEX';
export const SET_PROCESSINPUTOUT_ITEM = 'SET_PROCESSINPUTOUT_ITEM';

export const SET_DOWNPARTNAME = 'SET_DOWNPARTNAME';
export const SET_DOWNUPPCODE = 'SET_DOWNUPPCODE';

export const SET_PROCESSBADCODE_ITEM = 'SET_PROCESSBADCODE_ITEM';
export const SET_PROCESSBADCODE_TYPE = 'SET_PROCESSBADCODE_TYPE';
export const SET_PROCESSBADCODE_INDEX = 'SET_PROCESSBADCODE_INDEX';
export const SET_CHOOSEWAREHOUSE_ITEM = 'SET_CHOOSEWAREHOUSE_ITEM';
export const SET_CHOOSEWAREHOUSE_TYPE = 'SET_CHOOSEWAREHOUSE_TYPE';
export const SET_CHOOSEWAREHOUSE_INDEX = 'SET_CHOOSEWAREHOUSE_INDEX';
export const SET_PRODUCTDATA_NODATA = 'SET_PRODUCTDATA_NODATA';
export const SET_MODELSALEDETAIL_NODATA = 'SET_MODELSALEDETAIL_NODATA';
export const SET_SALERATIONODATA = 'SET_SALERATIONODATA';
export const SET_CARTONNOQUERY_QCCODE = 'SET_CARTONNOQUERY_QCCODE';
export const SET_MANYYIELD_DATA = 'SET_MANYYIELD_DATA';


